config/routes.rb
Blogger::Application.routes.draw do

  root to: "articles#index"

  get 'articles/remove_image' => 'articles#remove_image'
  resources :articles do
    resources :comments
  end

  get 'tags/delete_tagging' => 'tags#delete_tagging'
  resources :tags 

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :article_images

	def tags_list=(tags_string)
		tag_names= tags_string.split(",").collect { |tag| tag.strip.downcase }.uniq
		new_or_found_tags= tag_names.collect { |name| Tag.find_or_create_by(name: name) }
		self.tags= new_or_found_tags
	end

	def tags_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end

	def images_array=(images)
		images.each do |image|
			self.article_images.create(image: image)
		end
	end

	def images_array

	end

	
end

app/models/article_image.rb
class ArticleImage < ActiveRecord::Base
	
	belongs_to :article
	has_attached_file :image 
	validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png"]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	include ArticlesHelper

	def index
		@articles=Article.all
	end

	def show
		@article=Article.find(params[:id])
		@comment=Comment.new
		@comment.article_id=@article_id
	end

	def new
		@article=Article.new
	end

	def create
		@article=Article.create(article_params)
		@article.images_array = params[:article][:images_array]	
		flash.notice="'#{@article.title}' Created!"
		redirect_to @article
	end

	def destroy
		@article=Article.find(params[:id])
		@article.destroy
		flash.notice="'#{@article.title}' Deleted!"
		redirect_to articles_path
	end

	def edit
		@article=Article.find(params[:id])
	end

	def update
		@article=Article.find(params[:id])
		@article.images_array = params[:article][:images_array]
		@article.update(article_params)
		flash.notice="'#{@article.title}' Updated!"
		redirect_to @article
	end

	def remove_image
		@article_image=ArticleImage.find(params[:id])
		article_id=@article_image.article_id
		@article_image.destroy
		redirect_to edit_article_path(article_id)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def comment_params
		params.require(:comment).permit(:author_name, :body)		
	end

	def create
		@comment=Comment.new(comment_params)
		@comment.article_id=params[:article_id]
		@comment.save
		redirect_to @comment.article
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def show
		@tag=Tag.find(params[:id])		
	end

	def index
		@tags=Tag.all
	end

	def delete_tagging
		Tagging.find_by(article_id: params[:article_id], tag_id: params[:tag_id]).destroy
		redirect_to tag_path(params[:tag_id])
	end

	def destroy
		Tag.find(params[:id]).destroy
		redirect_to tags_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title,:body,:tags_list,:images_array)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
	<p>
		Comment by <%= comment.author_name %>  
	</p>
	<p>
		Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later
	</p>
	<p class="comment"> 
		<%= comment.body %> 
	</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {mutlipart: true}) do |f| %>
	<ul>
		<%= @article.errors.full_messages.each do |error| %>
			<li>
				<%= error %>
			</li>
		<% end %>
	</ul>
	<p>
		<%= f.label :title %></br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :tags_list %></br>
		<%= f.text_field :tags_list %>
	</p>
	<p>
		<%= f.label :body %></br>
		<%= f.text_area :body %>
	</p>
	<p>
		<% str="" %>
		<% if @article.article_images.exists? %>
			<% @article.article_images.each do |a| %>
				<div style="display:inline-block;">
					<%= image_tag a.image.url, width: "200px", height: "180px" %></br>
					<div align="center">
						<%= link_to "Remove", articles_remove_image_path(id: a.id) %>
					</div>
				</div>
			<% end %>
			<% str="Add More Images" %>
		<% else %>
			<% str="Add an Image" %>
		<% end %>
		</br></br>
		<%= f.label :images_array, str %></br>
		<%= f.file_field :images_array, multiple: true%>
	</p>
	</br></br>
	<p>
		<%= f.submit %>
	</p>
<% end %> 

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial:"form" %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<ul id="articles">
	<% @articles.each do |article| %>
		<li>
			<%= link_to article.title, article, class:"article_title", id:"article_#{article.id}" %>
		</li>
	<% end %>
</ul>
<%= link_to "Create a new article", new_article_path, class:"new_article" %>
<%= link_to "Tags", tags_path, class:"new_article tags" %>

app/views/articles/new.html.erb
<h1> Creating a new article </h1>
<%= render partial:"form" %>

app/views/articles/show.html.erb
<h1>
	<%= @article.title %>
</h1>
<p>
	Tags:
	<% @article.tags.each do |tag| %>
		<%= link_to tag.name, tag %>
	<% end %>
</p>
<p>
	<% if @article.article_images.exists? %>
		</br>
		</br>
		<% @article.article_images.each do |a| %>
			<%= image_tag a.image.url, width: "200px", height: "180px" %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<% end %>
	<% end %>
</p>
</br>
</br>
<p>
	<%= @article.body %>
</p>
</br>
</br>
<%= render partial:"comments/form" %>
</br>
<%= link_to "<<Back to Articles", articles_path %>
</br>
</br>
</br>
</br>
<%= link_to "Edit", edit_article_path(@article), class:"new_article edit" %> </t>
<%= link_to "Delete", @article, method: :delete, confirm:"Are you sure you want to delete this article?", class:"new_article" %>
<h4>Comments (<%= @article.comments.size %>) </h4>
</br>
<%= render partial: "comment", collection:@article.comments %>

app/views/comments/_form.html.erb
<h4>Post a Comment</h4>

<%= form_for [@article, @comment] do |f| %>
	<p>
		<%= f.label :author_name, "Your Name" %>
		<%= f.text_field :author_name %>
	</p>
	<p>
		<%= f.label :body, "Your Comment" %>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit "Submit"%>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash">
	<%= flash.notice %>
</p>
<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h1>
	List of Tags
</h1>

<ul id="articles">
	<% @tags.each do |tag| %>
		<li>
			<%= link_to tag.name.capitalize, tag %>
			<%= link_to "Delete", tag, method: :delete, class:"new_article remove" %>
		</li>
	<%end%>
</ul>

<%= link_to "Articles", articles_path, class:"new_article" %>

app/views/tags/show.html.erb
<h1>
	Articles for <%= @tag.name.capitalize %>
</h1>

<ul id="articles">
	<% @tag.articles.each do |article| %>
		<li>
			<%= link_to article.title, article %> 
			<%= link_to "Remove", tags_delete_tagging_path(article_id: article.id, tag_id: 
			@tag.id), class:"new_article remove" %>
		</li>
	<% end %>
</ul>

<%= link_to "Tags", tags_path, class:"new_article" %> 